#!/bin/bash

# Script: Automating API calls with shell

API_URL="https://pokeapi.co/api/v2/pokemon/"
OUTPUT_FILE="data.json" 
ERROR_FILE="errors.txt"

# Request with curl
curl -s -o "$OUTPUT_FILE" -w "%{http_code}" "$API_URL" > status_code.txt
STATUS_CODE=$(cat status_code.txt)

#check if the request is successful
if [ "$STATUS_CODE" -ne 200 ]; then
    echo "Error: Failed to fetch data from API. Status code: $STATUS_CODE" >> "$ERROR_FILE"
    rm -f "$OUTPUT_FILE"
fi

rm -f status_code.txt
