#!/bin/bash
# Script: Data extraction
#

name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')
weight=$(jq -r '.weight' data.json)
height=$(jq -r '.height' data.json)

#Height and weight conversion
weight_kg=$(awk "BEGIN {printf \"%.1f\", $weight/10}")
height_m=$(awk "BEGIN {printf \"%.1f\", $height/10}")
echo "$name is of type $type, weighs ${weight_kg}kg, and is ${height_m}m tall."
